// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: edison.proto

package edison_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Music *MusicStatus `protobuf:"bytes,1,opt,name=music,proto3" json:"music,omitempty"`
	Car   *CarStatus   `protobuf:"bytes,2,opt,name=car,proto3" json:"car,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edison_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_edison_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_edison_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetMusic() *MusicStatus {
	if x != nil {
		return x.Music
	}
	return nil
}

func (x *Msg) GetCar() *CarStatus {
	if x != nil {
		return x.Car
	}
	return nil
}

// musicStatus is a message with the current status of the music being played
//Not including isShuffled or artURL because mpris-proxy does not support it as of now
type MusicStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerName     string `protobuf:"bytes,1,opt,name=PlayerName,proto3" json:"PlayerName,omitempty"`
	PlaybackStatus string `protobuf:"bytes,2,opt,name=PlaybackStatus,proto3" json:"PlaybackStatus,omitempty"`
	// in milliseconds
	Length      int32  `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Artist      string `protobuf:"bytes,5,opt,name=Artist,proto3" json:"Artist,omitempty"`
	Album       string `protobuf:"bytes,6,opt,name=Album,proto3" json:"Album,omitempty"`
	AlbumArtist string `protobuf:"bytes,7,opt,name=AlbumArtist,proto3" json:"AlbumArtist,omitempty"`
	// in milliseconds from start
	Position int32 `protobuf:"varint,8,opt,name=Position,proto3" json:"Position,omitempty"`
}

func (x *MusicStatus) Reset() {
	*x = MusicStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edison_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusicStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicStatus) ProtoMessage() {}

func (x *MusicStatus) ProtoReflect() protoreflect.Message {
	mi := &file_edison_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicStatus.ProtoReflect.Descriptor instead.
func (*MusicStatus) Descriptor() ([]byte, []int) {
	return file_edison_proto_rawDescGZIP(), []int{1}
}

func (x *MusicStatus) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *MusicStatus) GetPlaybackStatus() string {
	if x != nil {
		return x.PlaybackStatus
	}
	return ""
}

func (x *MusicStatus) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *MusicStatus) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MusicStatus) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *MusicStatus) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *MusicStatus) GetAlbumArtist() string {
	if x != nil {
		return x.AlbumArtist
	}
	return ""
}

func (x *MusicStatus) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

//carStatus is a message with data from the obd2 sensor.
// Units in metric where applicable or a percentage from 0 to 1
type CarStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuelLevel     float32 `protobuf:"fixed32,1,opt,name=fuelLevel,proto3" json:"fuelLevel,omitempty"`
	CoolantTemp   int32   `protobuf:"varint,2,opt,name=coolantTemp,proto3" json:"coolantTemp,omitempty"`
	EngineLoad    float32 `protobuf:"fixed32,3,opt,name=engineLoad,proto3" json:"engineLoad,omitempty"`
	EngineRPM     float32 `protobuf:"fixed32,4,opt,name=engineRPM,proto3" json:"engineRPM,omitempty"`
	FuelPressure  uint32  `protobuf:"varint,5,opt,name=fuelPressure,proto3" json:"fuelPressure,omitempty"`
	VehicleSpeed  uint32  `protobuf:"varint,6,opt,name=vehicleSpeed,proto3" json:"vehicleSpeed,omitempty"`
	IntakeAirTemp int32   `protobuf:"varint,7,opt,name=intakeAirTemp,proto3" json:"intakeAirTemp,omitempty"`
}

func (x *CarStatus) Reset() {
	*x = CarStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edison_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStatus) ProtoMessage() {}

func (x *CarStatus) ProtoReflect() protoreflect.Message {
	mi := &file_edison_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStatus.ProtoReflect.Descriptor instead.
func (*CarStatus) Descriptor() ([]byte, []int) {
	return file_edison_proto_rawDescGZIP(), []int{2}
}

func (x *CarStatus) GetFuelLevel() float32 {
	if x != nil {
		return x.FuelLevel
	}
	return 0
}

func (x *CarStatus) GetCoolantTemp() int32 {
	if x != nil {
		return x.CoolantTemp
	}
	return 0
}

func (x *CarStatus) GetEngineLoad() float32 {
	if x != nil {
		return x.EngineLoad
	}
	return 0
}

func (x *CarStatus) GetEngineRPM() float32 {
	if x != nil {
		return x.EngineRPM
	}
	return 0
}

func (x *CarStatus) GetFuelPressure() uint32 {
	if x != nil {
		return x.FuelPressure
	}
	return 0
}

func (x *CarStatus) GetVehicleSpeed() uint32 {
	if x != nil {
		return x.VehicleSpeed
	}
	return 0
}

func (x *CarStatus) GetIntakeAirTemp() int32 {
	if x != nil {
		return x.IntakeAirTemp
	}
	return 0
}

var File_edison_proto protoreflect.FileDescriptor

var file_edison_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x64, 0x69, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x65, 0x64, 0x69, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x2f, 0x0a, 0x05, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x64, 0x69, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x6d,
	0x75, 0x73, 0x69, 0x63, 0x12, 0x29, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x65, 0x64, 0x69, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x63, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x63, 0x61, 0x72, 0x22,
	0xef, 0x01, 0x0a, 0x0b, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x6c,
	0x62, 0x75, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xf7, 0x01, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x75, 0x65, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x66, 0x75, 0x65, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x6f, 0x6f, 0x6c, 0x61, 0x6e, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x6c, 0x61, 0x6e, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x12,
	0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x4c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0a, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x4c, 0x6f, 0x61, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x50, 0x4d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x50, 0x4d, 0x12, 0x22, 0x0a,
	0x0c, 0x66, 0x75, 0x65, 0x6c, 0x50, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x66, 0x75, 0x65, 0x6c, 0x50, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x41,
	0x69, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x69, 0x6e,
	0x74, 0x61, 0x6b, 0x65, 0x41, 0x69, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x42, 0x10, 0x5a, 0x0e, 0x2e,
	0x3b, 0x65, 0x64, 0x69, 0x73, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_edison_proto_rawDescOnce sync.Once
	file_edison_proto_rawDescData = file_edison_proto_rawDesc
)

func file_edison_proto_rawDescGZIP() []byte {
	file_edison_proto_rawDescOnce.Do(func() {
		file_edison_proto_rawDescData = protoimpl.X.CompressGZIP(file_edison_proto_rawDescData)
	})
	return file_edison_proto_rawDescData
}

var file_edison_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_edison_proto_goTypes = []interface{}{
	(*Msg)(nil),         // 0: edison.proto.msg
	(*MusicStatus)(nil), // 1: edison.proto.musicStatus
	(*CarStatus)(nil),   // 2: edison.proto.carStatus
}
var file_edison_proto_depIdxs = []int32{
	1, // 0: edison.proto.msg.music:type_name -> edison.proto.musicStatus
	2, // 1: edison.proto.msg.car:type_name -> edison.proto.carStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_edison_proto_init() }
func file_edison_proto_init() {
	if File_edison_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_edison_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edison_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusicStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edison_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_edison_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edison_proto_goTypes,
		DependencyIndexes: file_edison_proto_depIdxs,
		MessageInfos:      file_edison_proto_msgTypes,
	}.Build()
	File_edison_proto = out.File
	file_edison_proto_rawDesc = nil
	file_edison_proto_goTypes = nil
	file_edison_proto_depIdxs = nil
}
